### ISSUE TITLE
IzzyOnDroid

### ISSUE THREAD

**Issue by Bnyro** [Bnyro/TriviaYou#1]
Hey @IzzySoft,
I would really appreciate if you could consider adding Trivia You to your repo :)
Please tell me if there's anything left that has to be done to make the app compatible with your repo.
Cheers
Bnyro

**Comment by IzzySoft** [comment]
Thanks for the call! Looks good, I've just added it, it will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.bnyro.trivia) tomorrow around 6 pm UTC (20:00 CEST).

Some minor adjustment to your Fastlane structure will be needed for the next release, so the screenshots are fetched as well: they must go one level deeper, inside `images/phoneScreenshots`. So can you please create `phoneScreenshots` inside `images` and move the screenshots inside? Thanks!

**Comment by Bnyro** [comment]
Wow, that was fast, thank you! Happy to be part of IzzyOnDroid now :p

PS: The screenshots should be fixed now :)

**Comment by IzzySoft** [comment]
Thanks! Confirming the screenshots are now in the correct place and will be pulled again with the next release (and future ones if they changed). Should you add more elements (like per-release changelogs, or a featureGraphic) please let me know so I can check and enable them as well.

**Comment by Bnyro** [comment]
Hey @IzzySoft,
changelogs were added now, would be great if you could pull them too :)

**Comment by IzzySoft** [comment]
Thanks, done! Will be reflected with the next sync around 6 pm UTC then.

**Comment by Bnyro** [comment]
Thank you!
