### ISSUE TITLE
Online competitive mode

### ISSUE THREAD

**Issue by panosalevropoulos** [Bnyro/TriviaYou#10]
Are there any plans to introduce online mode? It would make development much more complicated compared to an offline app, but it would be interesting to see a libre online trivia game.

**Comment by Bnyro** [comment]
A online mode would require some sort of hosted backend online which can cost a lot from time to time.
Apart from that I don't really have experiences with it, I probably lack experience for it.
To put it in a nutshell, there are no plans for an online mode, it's just not realizable.
