### ISSUE TITLE
Questions don't match category

### ISSUE THREAD

**Issue by JonnyTech** [Bnyro/TriviaYou#13]
**Describe the bug**
Selecting a category displays questions that belong to other categories.

**To Reproduce**
Select a category, ie film and tv
Question displayed is not about film and tv
Repeat category selection
More random questions displayed

**Expected behavior**
The displayed question should match the selected category

**Smartphone:**
 Android AOSP 11

**Suggestion**
Display the related category of each question
This would also help in general/random questions

**Comment by Bnyro** [comment]
Which API are you experience this issue with?
I tested it, for me it looks like it's working with TheTriviaAPI but not with the OpenTriviaDB

**Comment by JonnyTech** [comment]
I am using the default TheTriviaAPI and all questions seemed rather random. Maybe a corrupted database so I will reinstall the app. I see a new build released and shall check that this week.

**Comment by Bnyro** [comment]
OpenTriviaDatabase should work well now, TheTriviaAPI always worked for me in terms of categories, not sure

**Comment by JonnyTech** [comment]
I can confirm that OpenTriviaDatabase works correctly, but TheTriviaAPI still displays random questions not related to the selected category. Is there any log that I can check?

**Comment by JonnyTech** [comment]
Fixed in v0.14 - thank you.
