### ISSUE TITLE
Search feature not working

### ISSUE THREAD

**Issue by JonnyTech** [Bnyro/TriviaYou#15]
I am not sure exactly what the search bar should find but any search always returns nothing.

**Comment by Bnyro** [comment]
It works as intended, it searches your library for downloaded and self-created quizzes.

**Comment by JonnyTech** [comment]
Thanks. Created a question (note the unlabelled small buttons at the bottom - bug?):

![Screenshot_20220815-085839](https://user-images.githubusercontent.com/3584732/184599282-03139358-e445-4b59-aa1a-a78c1e5cdd28.png)

![Screenshot_20220815-085856](https://user-images.githubusercontent.com/3584732/184599338-3cc6f819-a8f5-4156-9da2-8165e3ae081c.png)

But search finds nothing:

![Screenshot_20220815-085918](https://user-images.githubusercontent.com/3584732/184599383-02b2de90-6b46-4e26-931d-7cf41e4341a1.png)

![Screenshot_20220815-085938](https://user-images.githubusercontent.com/3584732/184599452-fa4bfbe4-5cb1-494a-8cdb-14d840db4aba.png)

Is it possible to search within questions downloaded from TheTriviaAPI or OpenTriviaDB?

**Comment by Bnyro** [comment]
Yeah, the buttons thing look like a bug, I'll look into it.
It's not possible yet to search for specific questions, only for the name of the quiz so far. I'm planning to improve that in the future.

**Comment by JonnyTech** [comment]
Now that makes sense. Thank you.
