### ISSUE TITLE
Explanation of the "Unlimited mode" feature

### ISSUE THREAD

**Issue by maciej-klupp** [Bnyro/TriviaYou#16]
I want to translate the app to Polish, but I am not sure what exactly does the "Unlimited mode" feature do. 
A description of the feature, either an in-app one or one in the _strings.xml_ file meant just for translators, would make things more clear.

**Comment by Bnyro** [comment]
Unlimited mode means that when you are playing online (so not your own created quiz nor a downloaded one), it will just never stop to show new questions.
When the option is disabled, after the question amount limit you set in the settings (5 to 50), it will show a result screen showing how many questions were right or wrong.
I'll try to find out how to add this to Weblate to make other translators know about it, thank you for asking :)

**Comment by Bnyro** [comment]
I added and explanation to Weblate now, thank you for translating the app!
