### ISSUE TITLE
0.11 Changelog error

### ISSUE THREAD

**Issue by maciej-klupp** [Bnyro/TriviaYou#19]
I did the Polish translation, however in the release notes the Czech translation is attributed to me.
![obraz](https://user-images.githubusercontent.com/100523238/187170889-36ad0836-a4b6-4cfd-96a1-aa89c51153fa.png)

**Comment by Bnyro** [comment]
Oh, I'm sorry, that was my bad.
I don't think I can change it anymore, I'll just add it as additional info in the next release that it was polish :)
