### ISSUE TITLE
Sometimes questions don't fit on the screen

### ISSUE THREAD

**Issue by TheLastProject** [Bnyro/TriviaYou#2]
**Describe the bug**
Sometimes questions don't fit on the screen.

**To Reproduce**
1. Open the app
2. Answer questions until this happens

**Expected behavior**
It is always possible to see the question.

**Screenshots**
![Screenshot_20220728-000704_Trebuchet](https://user-images.githubusercontent.com/1885159/181436868-cc349196-a083-4d31-8da2-22d631e7f4ae.png)

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 - OS: Android 11 (LineageOS for microG)
 - Browser: It doesn't run in a browser? Do you mean WebView version? That is Android System WebView 102.0.5005.78
 - Version: 0.3
 
**Additional context**
Got the app from IzzyOnDroid

**Comment by Bnyro** [comment]
Hey :)
First of all thank you for using the app!
That's something I'll definitely have to look into, answering a question without knowing it can be a bit hard :D
Cheers

PS: The desktop and browser info isn't useful here, I just used the default issue Github issue template without watching it :p

**Comment by Bnyro** [comment]
We're using a hardcoded button height and auto text size now, therefore the issue shouldn't persist anymore :)
I'll update the app later today, it'll probably be updated on IzzyOnDroid at 6 pm UTC.

**Comment by JonnyTech** [comment]
Just to reopen this, can you make the **question** scrollable so that it can be read when the text is too long?

![Screenshot_20220731-100827](https://user-images.githubusercontent.com/3584732/182019689-eb2b265d-b35f-4091-a1fe-528c31825325.png)
