### ISSUE TITLE
Upgrading gradle wrapper version in GitHub actions and verifying Wrapper JAR manually 

### ISSUE THREAD

**Issue by LokNplay** [Bnyro/TriviaYou#28]
How about upgrading gradle wrapper version using ci.yml during building the app in GitHub actions?
Also you can verify Wrapper JAR manually of you want as a warning is shown in github actions "Node.js 12 actions are deprecated."

**Comment by Bnyro** [comment]
Hey,
thanks for your interest in the app!
Currently, I neither have really time nor motivation to work on the app (except merging translations ;)) as I think it's pretty much finished and has all the features I wanted to add to it.
I'd still accept any PRs if there are some, so if you want to do so feel free to create a PR :)
Cheers

**Comment by LokNplay** [comment]
Okay no problem
I will do a PR then.
But it's just about updating the ci.yml and yes I agree that the app is pretty much complete.

I am closing this issue and thanks again for your app.
