### ISSUE TITLE
Amoled black theme

### ISSUE THREAD

**Issue by Toiletmason** [Bnyro/TriviaYou#3]
Love the app. I get functionality is priority, but I'd like to see a black theme added.

**Comment by Bnyro** [comment]
Happy that you enjoy using the app :)
Adding a black theme is a good idea, I'll do it later ;)

I'm currently running out of ideas what else could be added so feel free to suggest other things too :p
(I'm still looking for some other Quiz APIs that could be used without signing in but couldn't find any :/)
