### ISSUE TITLE
Trivia languages

### ISSUE THREAD

**Issue by demonspanther** [Bnyro/TriviaYou#31]
Will the trivia questions and answers be translated in different languages?

**Comment by JonnyTech** [comment]
You probably need to request it from the question providers:

[The Trivia API](https://the-trivia-api.com/)
[Open Trivia DB](https://opentdb.com/)

**Comment by Bnyro** [comment]
Yes, I would be open for adding support for an API that supports multiple languages. However I did my best to find any that's public but didn't have any success, I ended up finding only `The Trivia API` and the `Open Trivia DB` which both are English only unfortunately. Translating the texts automatically via a third party API like Lingva doesn't make sense to me as it would quite often destroy the sense of the question and therefore it's not clear anymore what's even being asked for.
