### ISSUE TITLE
Make an option for time left on the correct answer.

### ISSUE THREAD

**Issue by Toiletmason** [Bnyro/TriviaYou#4]
Add an option for a set amount of time between questions. Sometimes when you get them wrong you don't have enough time to read the correct answer.

**Comment by Bnyro** [comment]
Yes, that's a good idea :)
I got a weird idea: one option could also be to make the time depend on the amount of words of the correct answer, like 500ms for each word :D

**Comment by Toiletmason** [comment]
@Bnyro is that's something that you think you can do then to for it. 👍

**Comment by JonnyTech** [comment]
Can you add an option for an infinite wait and advance with a next button? Some questions are good talking points so we like to chat about them before moving on to the next one.

**Comment by Bnyro** [comment]
@JonnyTech Sure, that's a good idea, I will add something like that later :)

**Comment by Bnyro** [comment]
@JonnyTech added in [496fe5a](https://github.com/Bnyro/TriviaYou/commit/496fe5a1f5f06db53195ca3c087fd8379afa07a3), will be available in the next update. You can get to the next question by pressing any button after you answered the question.

**Comment by JonnyTech** [comment]
Nice one @Bnyro, that was fast! Thank you very much.
