### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by Bnyro** [Bnyro/TriviaYou#5]
I'm not happy with the current app icon but lack creativity to imagine what it could be.
The current doesn't really have anything to do with trivia and looks really boring.
I'm happy about any suggestions :)

**Comment by JonnyTech** [comment]
To be honest, I quite like the current logo...

Anyway, a quick DDG search for question images that are "Free to Modify, Share, and Use Commercially" resulted in a couple that are nice (both from https://proofmart.com/).

![541-38-1536x1536-4037382578](https://user-images.githubusercontent.com/3584732/182369000-4d5913e6-e23a-42af-9308-91f045002bed.png)

![th-3803404926](https://user-images.githubusercontent.com/3584732/182368661-1b20b217-c8a1-4e16-bb40-236fe5ae8d97.jpg)

**Comment by Bnyro** [comment]
Hmm, these at not bad but they don't have anything in common with the design flavor of Material You :)

I agree, the current logo isn't too bad, but when seeing a star only as icon I probably wouldn't think that it's a quiz app :p
