### ISSUE TITLE
Build nightly version via Actions

### ISSUE THREAD

**Issue by airon90** [Bnyro/TriviaYou#7]
You can let GitHub build your app after every commit so that everyone can test each change and report bugs or features.

See https://github.com/z-huang/music/blob/dev/.github/workflows/build.yml or https://github.com/billthefarmer/gurgle/blob/main/.github/workflows/build.yml

**Comment by Bnyro** [comment]
Yeah, I'm aware, we're already doing that at [LibreTube](https://github.com/libre-tube/libretube). I'll enable it later ;)
